config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  root :to => redirect('/books/summary')

  resource :books do
    get "shelf"
    get "summary"
    get "search"
    get "more_info"
    post "search_results"
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
  has_and_belongs_to_many :books
end

app/models/book.rb
class Book < ApplicationRecord
  has_and_belongs_to_many :authors
  has_and_belongs_to_many :categories
  has_many :user_reads
end

app/models/category.rb
class Category < ApplicationRecord
  has_and_belongs_to_many :books
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/user_read.rb
class UserRead < ApplicationRecord
  belongs_to :book
  belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def after_sign_out_path_for(resource_or_scope)
    user_session_path
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def shelf
    @read_books = UserRead.where(user: current_user, status: 'read').order("created_at DESC")
    @want_to_read_books = UserRead.where(user: current_user, status: 'want_to_read')
  end

  def summary
    @read_books = UserRead.where(user: current_user, status: 'read').order("created_at DESC")
    @want_to_read_books = UserRead.where(user: current_user, status: 'want_to_read')
    @most_recent_read = UserRead.where(user: current_user).last
    @total_books_read = UserRead.where(user: current_user).count
  end

  def search 
    @book = Book.new
  end

  def more_info
    @book = Book.find(params['id'])
  end

  def search_results
    @books = GoogleBooks.search(book_params['title'], {:count => 10})
  end

  #move to user read controller
  def destroy
    book = Book.find_by(id: params['id'])
    UserRead.find_by(user: current_user, book: book).destroy
    current_user.reload
    redirect_to root_path
  end

  #more to user read controller
  def update
    book = Book.find(params['id'])
    read = UserRead.find_by(user: current_user, book: book)
    read.update(status: 'read')
    redirect_to root_path
  end

  private

  def book_params
    params.require(:book).permit(:title)
  end

  def create_authors(names)
    created_authors = []

    Array(names).each do |name|
      created_authors << Author.find_or_create_by(name: name)
    end

    created_authors
  end

  def create_user_read(book, status)
    UserRead.create(user: current_user, book: book, rating: 5, status: params['status'])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/books/index.html.erb
Can u see this

app/views/books/more_info.html.erb
<% read = UserRead.find_by(book: @book, user: current_user) %>

<div class="row align-items-start">
  <div class="col-1">
    <img src="<%= @book&.image_link %>" class="img-fluid rounded-start" alt="..." style="">
  </div>
  <div class="col-6">
    <div class="container">
      <p class="h1">
      <%= @book.title %>
      </p>

      <p class="h6">
        <%= @book.isbn %>
      </p>
      <p class="h5">
        <%= @book.description %>
      </p>
    </div>
  </div>
</div>

app/views/books/search.html.erb
<div class="container">
  <div class="text-container">
    <h2>Search book by title</h2>
  </div>

  <%= simple_form_for @book, :url => search_results_books_path do |f| %>
    <%= f.input :title, input_html: { class: 'search-input' }, label_html: { class: 'search-label' } %>
    <%= f.button :submit, 'Search', class: 'search-btn btn btn-secondary' %>
  <% end %>
</div>

app/views/books/search_results.html.erb
<div class="container">
  <div class="row">
    <% @books.each do |book| %>
      <div class="card m-2" style="max-width: 540px;">
        <div class="row g-0">
          <div class="col-md-4">
            <img src="<%= book&.image_link %>" class="img-fluid rounded-start" alt="..." style="height: 10vw; object-fit: cover;">
          </div>
          <div class="col-md-8">
            <div class="card-body">
              <h5 class="card-title"><%= book.title.truncate(30) %></h5>
              <p class="card-text"><%= book&.description&.truncate(100) %></p>
              <p class="card-text"><small class="text-muted">ISBN: <%= book&.isbn %></small></p>
              <div style="display: flex;">
                <%= button_to "Read",
                   {
                    :controller => :books,
                    :action => "create",
                    :title => book.title,
                    :authors => book.authors,
                    :description => book.description,
                    :isbn => book.isbn,
                    :image_link => book.image_link,
                    :status => "read"
                  },
                  :method => :post,
                  class: "btn btn-secondary mr-1"
                %>
                <%= button_to "Want to read",
                   {
                    :controller => :books,
                    :action => "create",
                    :title => book.title,
                    :authors => book.authors,
                    :description => book.description,
                    :isbn => book.isbn,
                    :image_link => book.image_link,
                    :status => "want_to_read"
                  },
                  :method => :post,
                  class: "btn btn-secondary"
                  %>
              </div>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/books/shelf.html.erb
<script src="https://code.iconify.design/2/2.1.0/iconify.min.js"></script>

<div class="parent-container">
  <div class="container">
    <p class="text-center h1">
      Read
    </p>
    <div class="row border-right">
      <% if @read_books %>
        <% @read_books.each do |read| %>
          <% book = read.book %>
          <div class="m-3 test">
            <img src="<%= book&.image_link %>" class="img-fluid rounded-start" alt="..." style="height: 10vw; width: 6.5vw; object-fit: cover;">
            <div class="hover-text">
              <%= link_to "More Info", more_info_books_path(:id => book.id), :method => :get %>
              <%= button_to books_path(:id => book.id), method: :delete do %>
                <span class="iconify" data-icon="bi:trash-fill" style="color: #FFBD00; background-color: transparent; border: none;" data-width="35" data-height="35"></span>
              <% end %>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>

  <div class="container">
    <p class="text-center h1">
      Want to Read
    </p>
    <div class="row">
      <% if @want_to_read_books %>
        <% @want_to_read_books.each do |read| %>
          <% book = read.book %>
          <div class="m-3 test" style="position: relative;">
            <img src="<%= book&.image_link %>" class="img-fluid rounded-start" alt="..." style="height: 10vw; object-fit: cover;">
            <div class="hover-text">
              <%= link_to "More Info", more_info_books_path(:id => book.id), :method => :get %>
              <%= button_to books_path(:id => book.id), method: :delete do %>
                <span class="iconify" data-icon="bi:trash-fill" style="color: #FFBD00; background-color: transparent; border: none;" data-width="35" data-height="35"></span>
              <% end %>
              <%= button_to books_path(:id => book.id), method: :patch do %>
                <span class="iconify" data-icon="eva:checkmark-circle-2-outline" data-width="40" data-height="40"></span>
              <% end %>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/books/summary.html.erb
<script src="https://code.iconify.design/2/2.1.0/iconify.min.js"></script>

<div class="parent-container">
  <div class="container" style="display: flex; align-items: center;">
    <div class="m-3 test">
      <img src="<%= @most_recent_read.book.image_link %>" class="img-fluid rounded-start" alt="..." style="height: 10vw; width: 6.5vw; object-fit: cover;">
    </div>
    <p class="text-center h2">
      Most Recent Read: <%= @most_recent_read.book.title %>
    </p>
  </div>

  <div class="container">
    <p class="text-center h1">
      Total books read: <%= @total_books_read %>
    </p>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BetterBookKeeper</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="df">
      <%= render 'shared/sidebar' %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_sidebar.html.erb
<body>
  <main>
    <div class="d-flex flex-column flex-shrink-0 p-3 text-white bg-dark" style="width: 280px;">
      <a href="/" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto text-white text-decoration-none">
        <svg class="bi me-2" width="40" height="32"><use xlink:href="#bootstrap"/></svg>
        <span class="fs-4">Book Keeper</span>
      </a>
      <hr>
      <ul class="nav nav-pills flex-column mb-auto">
        <li class="nav-item">
          <a href="<%= summary_books_path %>" class="nav-link active" aria-current="page">
            <svg class="bi me-2" width="16" height="16"><use xlink:href="#home"/></svg>
            Home
          </a>
        </li>
        <li>
          <a href="<%= shelf_books_path %>" class="nav-link text-white">
            <svg class="bi me-2" width="16" height="16"><use xlink:href="#speedometer2"/></svg>
            Shelf
          </a>
        </li>
        <li>
          <a href="<%= search_books_path %>" class="nav-link text-white">
            <svg class="bi me-2" width="16" height="16"><use xlink:href="#table"/></svg>
            Search
          </a>
        </li>
      </ul>
      <hr>
      <div class="dropdown">
        <% if user_signed_in? %>
          <form class="form-inline my-2 my-lg-0">
            <%= link_to "Log out", destroy_user_session_path, :method => :delete, :style => 'color:#66FCF1;' %>
          </form>
        <% else %>
          <form class="form-inline my-2 my-lg-0 navbar-text">
            <%= link_to "Log in", user_session_path, :method => :post, :style => 'color:white;' %>
            <%= link_to "Sign up", new_user_registration_path, :method => :get, :style => 'color:#66FCF1;' %>
          </form>
        <% end %>
      </div>
    </div>
  </main>
</body>